---
- name: Prepare
  hosts: all

  pre_tasks:
    - name: Update apt cache (on Debian).
      apt:
        update_cache: true
        cache_valid_time: 3600
      when: ansible_os_family == 'Debian'

    - name: Update yum cache (on Redhat).
      yum:
        update_cache: true
      when: ansible_os_family == 'RedHat'

  tasks:
    - name: Remove local users
      user:
        name: ansible
        state: present

    - name: Remove local groups
      group:
        name: ansible
        state: present

    - name: Add local groups
      group:
        name: department99
        state: present
