---
name: CI

on:
  pull_request:
  schedule:
    - cron: '37 4 12 * *'

jobs:

  lint:
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2.4.0

      - name: Lint Code Base
        uses: github/super-linter@v4.8.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  molecule:
    needs: lint
    name: Molecule
    runs-on: ubuntu-latest

    steps:
      - name: Check out the codebase
        uses: actions/checkout@v2.4.0

      - name: Set up Python 3
        uses: actions/setup-python@v2.2.2
        with:
          python-version: "3.x"

      - name: Install Tox
        run: |
          pip3 install tox

      - name: Run Molecule tests
        run: tox
        env:
          PY_COLORS: "1"
          ANSIBLE_FORCE_COLOR: "1"
